### ISSUE TITLE
Broken post URLs

### ISSUE THREAD

**Issue by thefoxis** [bigboringsystem/bigboringsystem#166] opened 2015-01-09 14:11 UTC
I just noticed some post urls seem to be broken. I wanted to link to my first post from **Dec 29th, 2014 - 08:11 am** and:

```
https://bigboringsystem.com/post/post!undefined
```

is its link.

**Comment by jasonrhodes** [comment] 2015-01-09 14:44
It seems like the split is sometime around the morning of Dec 30, with anything older than that split getting a `post!undefined` slug in the generated URL in /discover and in /posts

I'm not 100% sure but it seems like it might be related to the post ID work mentioned in #59 and #57, @isaacs and @ednapiranha will obviously know better. I'm gonna try reverting locally to before those merges, saving a few posts, and then switching back to latest master to see if I can duplicate the problem.

**Comment by jasonrhodes** [comment] 2015-01-09 15:08
OK confirmed that #59 is the split. To reproduce locally you would:

* `git checkout -b old-test-before a8524c5543c70531659aa84274a433818a30a54b~1` (goes back to commit right before the #59 merge)
* Update lib/utils.js to mock out the client, commit in this test branch
```
// var client = twilio(nconf.get('twilioSID'), nconf.get('twilioToken'))
var client = { sendMessage: function (opts, cb) { cb(); }};
```
* Log in, create a post or two
* `git checkout -b old-test-after a8524c5543c70531659aa84274a433818a30a54b && git merge old-test-before`
* Refresh page, create another post
* `git checkout master`
* The post created in `old-test-before` will have the `post!undefined` URL, the post created in `old-test-after` will have the correct URL.

I'll be doing work things for a while, if no one else makes any progress based on this info I'll take a look again later to see if I can figure out what happened there to cause this.

**Comment by jalcine** [comment] 2015-01-09 15:08
Three cheers for @jasonrhodes :beers:

**Comment by jasonrhodes** [comment] 2015-01-09 15:12
Oh, important to note: #59 didn't cause this bug to appear right then. In the `old-test-after` branch above, the post urls are all working fine. It's something that happened between #59 and now that causes the bug, but it's related to the changes in 59 because that's where the split between broken posts and non-broken posts is...

**Comment by jasonrhodes** [comment] 2015-01-09 15:17
Ok ok more info: found where the bug is introduced, it's #86, which was merged on sha c6baaf5fc134b8db97996fbcbbb5db1f0fea2569

If you checkout that sha, the posts created in my earlier steps have the bug, if you checkout that sha ~1, the url bug is gone.

**Comment by jasonrhodes** [comment] 2015-01-09 16:48
Seems like @isaacs is on the case somewhat, too: https://bigboringsystem.com/post/post!1420819909-3f

**Comment by isaacs** [comment] 2015-01-09 23:15
The best fix, I think, is a migration script that does `if (!post.postid) { post.postid = post.created; save() }` on each of the objects in the `posts` database.

The other option is to have the discover and posts pages show `post.postid || post.created` in the URLs, but that's kinda gross, since it adds complexity for a fixable problem.

**Comment by ednapiranha** [comment] 2015-01-09 23:16
we're doing some migrations right now so doing that script is easy. i'll set it up

**Comment by ednapiranha** [comment] 2015-01-10 00:07
https://github.com/bigboringsystem/bigboringsystem/commit/fd105b26075ceea3bb4f99050af225aaef1199cf

**Closed by ednapiranha** 2015-01-10 00:07 UTC
Labels: bug
