### ISSUE TITLE
Reply notifications

### ISSUE THREAD

**Issue by coleGillespie** [bigboringsystem/bigboringsystem#123] opened 2015-01-06 03:59 UTC
Would be nice if users could have a way of being notified if someone has replied to one of their posts. This way the conversation could continue. Maybe a conversations page?

**Comment by coleGillespie** [comment] 2015-01-06 14:15
maybe the posts page could show replies?

**Comment by isaacs** [comment] 2015-01-07 00:57
Duplicate of #61 and #35.  Partly addressed by #138.  A page that just shows all replies to all of your posts would be interesting.

**Closed by isaacs** 2015-01-07 00:57 UTC
Labels: enhancement, philosophy
